server:
  port: 8080
spring:
  application:
    name: turntable
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://82.156.234.232:3306/turntable?serverTimezone=GMT%2B8
    url: jdbc:mysql://82.156.234.232:3306/turntable
    username: root
    password: 123456